[tool.poetry]
name = "rag"
version = "0.1.0"
description = ""
authors = ["Egorov E.A. <emelya.kara@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
transformers = "^4.46.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
